language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mohamedkamal91/reverseproxy
  - docker push mohamedkamal91/udagram-api-user
  - docker push mohamedkamal91/udagram-api-feed
  - docker push mohamedkamal91/udagram-frontend