apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: frontend
        image: mohamedkamal91/udagram-frontend:v1
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        imagePullPolicy: Always 
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"   
        ports:
        - containerPort: 80
